NUMpy


In [3]:
import numpy as np


In [5]:
print(np.__version__)

1.26.4


In [8]:
x1=np.array([1,2,55,66,88])
print(x1)
print(type(x1))
print(x1.ndim)
print(x1.shape)


[ 1  2 55 66 88]
<class 'numpy.ndarray'>
1
(5,)


In [10]:
## 2d/Matrix

In [12]:
x2=np.array([[1,2,55,66,88],[2,3,4,5,6]])
print(x2)
print(type(x2))
print(x2.ndim)
print(x2.shape)


[[ 1  2 55 66 88]
 [ 2  3  4  5  6]]
<class 'numpy.ndarray'>
2
(2, 5)


In [15]:
x3=np.array([[[1,2,55,66],[2,3,4,5]],[[7,8,9,10],[4,5,6,77]]])
print(x3)
print(type(x3))
print(x3.ndim)
print(x3.shape)


[[[ 1  2 55 66]
  [ 2  3  4  5]]

 [[ 7  8  9 10]
  [ 4  5  6 77]]]
<class 'numpy.ndarray'>
3
(2, 2, 4)


In [17]:
##3d//vector

In [19]:
x4=np.array([[[1,2,55,66],[2,3,4,5]],[[7,8,9,10],[4,5,6,77]],[[2,3,4,5],[7,10,12,11]]])
print(x4)
print(type(x4))
print(x4.ndim)
print(x4.shape)


[[[ 1  2 55 66]
  [ 2  3  4  5]]

 [[ 7  8  9 10]
  [ 4  5  6 77]]

 [[ 2  3  4  5]
  [ 7 10 12 11]]]
<class 'numpy.ndarray'>
3
(3, 2, 4)


In [22]:
x5=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x5)
print(type(x5))
print(x5.ndim)
print(x5.shape)
print("_"*30)
x6=x5.reshape(6,2)
print(x6)
print(x6.ndim)
print(x6.shape)
print("_"*30)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
1
(12,)
______________________________
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
2
(6, 2)
______________________________


In [24]:
##1dto3dconversion

In [26]:
x7=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x7)
print(type(x7))
print(x7.ndim)
print(x7.shape)
print("_"*30)
x8=x7.reshape(3,2,2)
print(x8)
print(x8.ndim)
print(x8.shape)
print("_"*30)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
1
(12,)
______________________________
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)
______________________________


In [28]:
##two variable soln

In [30]:
a=np.array([[20,12],[-5,10]])
b=np.array([8,21])
sol=np.linalg.solve(a,b)
print(sol)



[-0.66153846  1.76923077]


In [32]:
##3variable soln

In [34]:
a1=np.array([[10,-9,4],[52,19,16],[5,7,-10]])
b1=np.array([12,17,28])
sol=np.linalg.solve(a1,b1)
print(sol)



[ 1.47576253 -0.88562092 -2.68205338]


In [36]:
from matplotlib.image import imread
hi=imread("C://Users//madhu//OneDrive//Pictures//weic2212a.jpg")
print(hi)
print(type(hi))
print(hi.ndim)
print(hi.shape)

[[[102  28  19]
  [ 99  29  19]
  [ 95  28  19]
  ...
  [ 21  21  29]
  [ 21  27  39]
  [ 30  38  51]]

 [[112  32  25]
  [105  30  24]
  [ 98  28  20]
  ...
  [ 20  21  26]
  [ 19  23  32]
  [ 25  31  43]]

 [[116  33  29]
  [109  30  25]
  [ 99  26  19]
  ...
  [ 21  20  25]
  [ 16  19  24]
  [ 20  25  31]]

 ...

 [[ 63  47  34]
  [ 57  41  28]
  [ 53  37  24]
  ...
  [105  47  33]
  [106  48  34]
  [104  48  33]]

 [[ 67  51  38]
  [ 60  44  31]
  [ 55  39  26]
  ...
  [109  46  31]
  [112  50  35]
  [106  47  31]]

 [[ 68  52  37]
  [ 61  45  32]
  [ 57  41  28]
  ...
  [111  44  28]
  [117  50  34]
  [111  45  31]]]
<class 'numpy.ndarray'>
3
(1536, 2048, 3)


In [38]:
##matrix solving

In [40]:
test=np.array([[40,20,20],[4,5,6],[30,40,20]])
print(test)
print("_"*30)
print(np.linalg.matrix_rank(test))
print("-"*30)
print(np.trace(test))
print("_"*30)
print(np.linalg.det(test))
print("_"*30)
print(np.linalg.inv(test))
print("_"*30)


[[40 20 20]
 [ 4  5  6]
 [30 40 20]]
______________________________
3
------------------------------
65
______________________________
-3399.999999999999
______________________________
[[ 0.04117647 -0.11764706 -0.00588235]
 [-0.02941176 -0.05882353  0.04705882]
 [-0.00294118  0.29411765 -0.03529412]]
______________________________


In [42]:
##eigen value

In [44]:
test1=np.array([[1,2,3],[5,6,7],[9,10,11]])
print(test1)
print()
c,d=np.linalg.eig(test1)
print(c)
print()
print(d)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[ 1.92469508e+01 -1.24695077e+00  1.32811035e-15]

[[ 0.1937289   0.77433837  0.40824829]
 [ 0.51451855  0.07288936 -0.81649658]
 [ 0.83530819 -0.62855964  0.40824829]]


In [46]:
##mean,median,mode

In [48]:
from scipy import stats
speed=np.array([22,44,55,66,77,88,99,33,12,45,44,32,66,76,5,22,22,0,14])
m=np.mean(speed)
print(m)
m1=np.median(speed)
print(m1)
m2=stats.mode(speed)
print(m2)

43.26315789473684
44.0
ModeResult(mode=22, count=3)


In [52]:
speed=np.array([22,44,77,88,99,33,12,55,66,77,99])
print(speed.std())
print(speed.var())


28.89622355148143
834.9917355371902


In [ ]:
##percentile

In [54]:
speed=np.array([22,44,77,88,99,33,12,55,66,77,99])
np.percentile(speed,80)


88.0